
server:
  port: 7001
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wjq17/config-repo/
          search-paths: config-repo
          username: 
          password: 
